baseURL: https://blog.0x74696d.com/
disablePathToLower: true
languageCode: en-us
title: "0x74696d"
publishDir: "build"
PygmentsCodeFences: true
pygmentsuseclasses: true
rssLimit: 20

markup:
  goldmark:
    extensions:
      typographer: false
    renderer:
      unsafe: true

params:
  author: "Tim Gross"
  github: "tgross"
  twitter: "0x74696d"
  description: "T-Minus 15.193792102158E+9 years until the universe closes!"
  mainSections:
    - "posts"

taxonomies:
  category:
...
